<?php

namespace AdminBundle\Repository;

/**
 * HoliTyeslistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoliTyeslistRepository extends \Doctrine\ORM\EntityRepository
{
}
