# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     my.handler.session_idle:
          class: UserBundle\Listener\SessionIdleHandler
          arguments: ["@session", "@security.context", "@router", %session_max_idle_time%,"@service_container"]
          tags:
                     - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
     add.user.headers.listener:
           class: UserBundle\Listener\AddUserInfoHeaderListener
           arguments: ["@security.context"]
           tags:
               - { name: kernel.event_subscriber }